version: '3'
services:
  common:
    container_name: common
    build: ./common
    ports:
      - "8081:8081"
    restart: always
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul

  funding:
    container_name: funding
    build: ./funding
    ports:
      - "8082:8082"
    restart: always
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul

  pay:
    container_name: pay
    build: ./pay
    ports:
      - "8083:8083"
    restart: always
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul

  alert:
    container_name: alert
    build: ./alert
    ports:
      - "8084:8084"
    restart: always
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul

networks:
  default:
    driver: bridge
